### ISSUE TITLE
兄弟，如何使用啊？原生看不懂。。

### ISSUE THREAD

**Issue by Mad-hu** [smartliang/react-native-alarm#2]
兄弟，这个怎么用啊？，原生看不懂  !!~~，上个demo呗。

**Comment by smartliang** [comment]
readme中增加了调用方法

**Comment by Mad-hu** [comment]
`let time = '2017-11-07 17:57:00';
 let timestamp = Moment(time).format('x');
            RNAlram.setAlarm(
                timestamp,
                '***今天过生日',
                "",
                "",
                (result)=>{
                    console.log('Set successful');
                    console.log(result);
                },
                (result)=>{
                    console.log('Set error');
                    console.log(result);
                });`

**Comment by smartliang** [comment]
是的
